### ISSUE TITLE
can you include instructions how to use this function in Trino/Presto as well

### ISSUE THREAD

**Issue by sanjay92-gupta** [yuokada/presto-sample-udf#19]
There are no test case how to basically use or test whatever UDF function was created. It would be great, if you could also provide how to use this in Presto or Trino

**Comment by sanjay92-gupta** [comment]
when even doing this 
% mkdir /usr/lib/presto/lib/plugin/hello/
% cp target/presto-sample-udf-1.0-SNAPSHOT.jar /usr/lib/presto/lib/plugin/hello/
% /usr/lib/presto/bin/launcher restart

Trino is not even starting
2023-04-19T22:15:56.741Z	ERROR	main	io.trino.server.Server	No service providers of type io.trino.spi.Plugin in the classpath: [file:/usr/lib/trino/plugin/hello/presto-sample-udf-1.5-SNAPSHOT.jar]
java.lang.IllegalStateException: No service providers of type io.trino.spi.Plugin in the classpath: [file:/usr/lib/trino/plugin/hello/presto-sample-udf-1.5-SNAPSHOT.jar]
	at com.google.common.base.Preconditions.checkState(Preconditions.java:821)
	at io.trino.server.PluginManager.loadPlugin(PluginManager.java:164)
	at io.trino.server.PluginManager.loadPlugin(PluginManager.java:154)
	at io.trino.server.ServerPluginsProvider.lambda$loadPlugins$1(ServerPluginsProvider.java:58)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at java.base/java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:184)
	at io.trino.util.Executors.executeUntilFailure(Executors.java:41)
	at io.trino.server.ServerPluginsProvider.loadPlugins(ServerPluginsProvider.java:53)
	at io.trino.server.PluginManager.loadPlugins(PluginManager.java:136)
	at io.trino.server.Server.doStart(Server.java:136)
	at io.trino.server.Server.lambda$start$0(Server.java:88)
	at io.trino.$gen.Trino_403_amzn_0____20230419_221545_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:88)
	at io.trino.server.TrinoServer.main(TrinoServer.java:38)
